### ISSUE TITLE
rucksack hangs on openssl s_client commands

### ISSUE THREAD

**Issue by str8edgedave** [acritelli/rucksack#3]
Hi Anthony,
I love Rucksack! I have noticed an issue. One of the commandlets I have built is to check ssl expiry dates on remote hosts using openssl. When I execute the commandlet, rucksack hangs until I press <Ctrl-c>, then it displays the output. The bash command is :
```bash
[david@localhost ~]$ openssl s_client -servername <HOSTNAME> -connect <HOST:PORT> 2>/dev/null | openssl x509 -noout -dates
```

The rucksack configuration looks like:
```yml
check-ssl-date:
  command: "openssl s_client -servername {{ server_name }} -connect {{ server_name }}:443 2>/dev/null | openssl x509 -noout -dates"
  args:
    - server_name:
        mandatory: True
        default: server1.domain.com
        values:
          - server1.domain.com
          - server2.domain.com
          - server3.domain.com
          - server4.domain.com
```

Output from rucksack looks like:
```bash
[david@localhost ~]$ ruck --host localhost
localhost> check-ssl-date server_name google.ca
Attempting to run openssl s_client -servername google.ca -connect google.ca:443 2>/dev/null | openssl x509 -noout -dates <Press Ctrl-c to continue here>
notBefore=Jan 17 03:48:17 2022 GMT
notAfter=Apr 11 03:48:16 2022 GMT


localhost>
Goodbye!
[david@localhost ~]$
```

OS: Fedora Linux 35 Server Edition
Python version: 3.10.2

**Comment by acritelli** [comment]
Hi @str8edgedave! I'm very happy to hear that you like Rucksack. And this is actually one of the commands that I use frequently as well!

I don't think the problem here is Rucksack. I've run into this "issue" as well with OpenSSL, and the specifics are escaping me at the moment. However, if you pipe an `echo` into the `openssl s_client` and set the `no_ign_eof` flag, it should work. For reasons that I can't recall, `s_client` will keep the connection open.

I was able to reproduce your issue and resolve it like so:

```
check-ssl-date:
  command: "echo | openssl s_client -no_ign_eof -servername {{ server_name }} -connect {{ server_name }}:443 2>/dev/null | openssl x509 -noout -dates"
  args:
    - server_name:
        mandatory: True
        default: www.acritelli.com
        values:
          - www.acritelli.com
          - www.github.com
```

The presence of the echo here causes the `s_client` to immediately terminate. Thus the command returns, and rucksack is able to display the output to you:

```
❯ ruck --host localhost
localhost> check-ssl-date
Attempting to run echo | openssl s_client -no_ign_eof -servername www.acritelli.com -connect www.acritelli.com:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Jan 20 02:33:51 2022 GMT
notAfter=Apr 20 02:33:50 2022 GMT
```

Please let me know if this resolves your issue!
